---
title: "Assignment_B-1"
author: "Tzu-Yi Lu"
date: "2021 Nov 02"
output: html_document
---

In my milestones 1~3 submitted to STAT545A, I kept extracting a specific subset from a current dataset. Therefore, I decided to  create a function that helps me with extracting a subgroup from the "vancouver_trees" dataset.

```{r}
#' @tilte Extracting a subset for the tree growth analysis
#' @description  This function calculates the tree age of each observation in the input and then extracts a subset from it according to the specified area(s).
#' @params input_data: The imported data for extracting a subset.
#' @params chosen_area: The areas you want.
#' @params ref_date: The reference date for calculating the tree age of each observation.
#' @return The observations of the input_data located in the "chosen_area".

#' 

library(dplyr)
library(tidyr)
extract_dat <- function(input_data,chosen_area,ref_date) {
  output_data <-input_data%>%
    mutate(tree_age = as.numeric(difftime(as.Date(ref_date),date_planted))/365) %>%
    drop_na() %>%
    filter(neighbourhood_name  %in% chosen_area)
  return(output_data)
  }

```

I named the function as "extract_dat", which means extracting data.

```{r}

# load the dataset from the "datateachr" package
library(datateachr)

chosen_area <- c("ARBUTUS-RIDGE","DUNBAR-SOUTHLANDS","KITSILANO","SHAUGHNESSY","WEST POINT GREY")
VanTreeUBC <- output_data(vancouver_trees, chosen_area, "2021-11-02")

```

