---
title: "Assignment_B-2"
author: "Tzu-Yi Lu, "
date: "2021 Nov 20"
output: github_document
---


# Exercise 1: Function(s)

## Loading required package: usethis
```{r}
library(devtools)

## Confirming package version of devtools
packageVersion("devtools") 

## Creating a new package named "ExtractData"
create_package("/Users/ziyi/GoogleDrive_p/My Drive/PhD/1_STAT545/Assignments/functions-tzuyilu/Assignment_B-2/ExtractData")

## Making the "ExtractData" directory also a Git repository
use_git()

## Creating two functions in this package
use_r("TreeAgeCal")
use_r("RegionSel")

## Rendering my functions
document()
```

# Exercise 2: High-level documentation
```{r}

```

# Exercise 3: DESCRIPTION file
```{r}
# Storing data in this package
use_r("vancouver_trees")

# Importing other packages
use_dev_package("dplyr")
use_dev_package("tidyr")
use_dev_package("datateachr")
use_dev_package("magrittr")

# Authorizing a licence
use_mit_license()

# Editting author information manually

```

# Exercise 4: Tests
```{r}
## Adding test functions in the package
use_test("TreeAgeCal")
use_test("RegionSel")
```
